/**
 * Declarative definitions for all language/tool setup shims.
 *
 * Each entry replaces a block of imperative bash-in-template-strings from
 * the old BUILTIN_SHIMS in resolver.ts. The ShimDefinition structure is
 * compiled into composite action YAML by generateShimActionYml().
 */
import type { ShimDefinition } from './shim-framework.js';

export const SHIM_DEFINITIONS: Record<string, ShimDefinition> = {

  // ── Python ──────────────────────────────────────────────────────────────

  'actions/setup-python': {
    name: 'Setup Python (local shim)',
    description: 'Local runner shim — uses system Python',
    inputs: {
      'python-version': { description: 'Python version', default: '3.x' },
      'cache': { description: 'Package manager to cache', default: '' },
      'architecture': { description: 'Architecture', default: 'x64' },
      'check-latest': { description: 'Check latest', default: 'false' },
      'token': { description: 'Token', default: '' },
      'cache-dependency-path': { description: 'Cache dependency path', default: '' },
      'update-environment': { description: 'Update env', default: 'true' },
      'allow-prereleases': { description: 'Allow prereleases', default: 'false' },
    },
    outputs: {
      'python-version': { description: 'Installed Python version' },
      'python-path': { description: 'Python executable path' },
      'cache-hit': { description: 'Cache hit' },
    },
    detect: [
      {
        name: 'pyenv',
        detect: [
          'REQUESTED="\\${{ inputs.python-version }}"',
          'if command -v pyenv &>/dev/null; then',
          '  AVAILABLE=$(pyenv versions --bare 2>/dev/null | grep "^$REQUESTED" | tail -1)',
          '  if [ -n "$AVAILABLE" ]; then',
          '    pyenv shell "$AVAILABLE"',
          '    echo "Using pyenv Python $AVAILABLE"',
          '    TOOL_FOUND="pyenv"',
          '  fi',
          'fi',
        ].join('\n'),
      },
      {
        name: 'system python',
        detect: [
          'PYTHON_PATH=$(command -v python3 || command -v python)',
          'if [ -n "$PYTHON_PATH" ]; then',
          '  TOOL_PATH="$PYTHON_PATH"',
          '  TOOL_FOUND="system"',
          'fi',
        ].join('\n'),
      },
    ],
    setup: [
      'PYTHON_PATH=$(command -v python3 || command -v python)',
      'PYTHON_VER=$($PYTHON_PATH --version 2>&1 | awk \'{print $2}\')',
      'echo "python-version=$PYTHON_VER" >> $GITHUB_OUTPUT',
      'echo "python-path=$PYTHON_PATH" >> $GITHUB_OUTPUT',
      'echo "cache-hit=false" >> $GITHUB_OUTPUT',
      'echo "Using Python $PYTHON_VER at $PYTHON_PATH"',
    ].join('\n'),
    notFoundMessage: 'Python not found. Install with: brew install python3',
  },

  // ── Java ────────────────────────────────────────────────────────────────

  'actions/setup-java': {
    name: 'Setup Java (local shim)',
    description: 'Local runner shim — uses system Java',
    inputs: {
      'java-version': { description: 'Java version', default: '17' },
      'distribution': { description: 'Distribution', default: 'temurin' },
      'java-package': { description: 'Package type', default: 'jdk' },
      'architecture': { description: 'Architecture', default: 'x64' },
      'check-latest': { description: 'Check latest', default: 'false' },
      'server-id': { description: 'Server ID for maven', default: '' },
      'server-username': { description: 'Server username env var', default: '' },
      'server-password': { description: 'Server password env var', default: '' },
      'settings-path': { description: 'Maven settings path', default: '' },
      'overwrite-settings': { description: 'Overwrite settings', default: 'true' },
      'gpg-private-key': { description: 'GPG private key', default: '' },
      'gpg-passphrase': { description: 'GPG passphrase env var', default: '' },
      'cache': { description: 'Build tool cache (maven, gradle, sbt)', default: '' },
      'token': { description: 'Token', default: '' },
    },
    outputs: {
      'java-version': { description: 'Installed Java version' },
      'java-home': { description: 'JAVA_HOME path' },
      'path': { description: 'Java bin path' },
    },
    detect: [
      {
        name: '/usr/libexec/java_home (macOS native)',
        detect: [
          'REQUESTED="\\${{ inputs.java-version }}"',
          'if [ -x /usr/libexec/java_home ]; then',
          '  FOUND_HOME=$(/usr/libexec/java_home -v "$REQUESTED" 2>/dev/null || true)',
          '  if [ -n "$FOUND_HOME" ] && [ -d "$FOUND_HOME" ]; then',
          '    TOOL_PATH="$FOUND_HOME"',
          '    TOOL_FOUND="java_home"',
          '  fi',
          'fi',
        ].join('\n'),
      },
      {
        name: 'SDKMAN',
        detect: [
          'REQUESTED="\\${{ inputs.java-version }}"',
          'if [ -d "${SDKMAN_DIR:-$HOME/.sdkman}" ]; then',
          '  SDK_DIR="${SDKMAN_DIR:-$HOME/.sdkman}"',
          '  CANDIDATE=$(find "$SDK_DIR/candidates/java" -maxdepth 1 -type d -name "*$REQUESTED*" 2>/dev/null | sort -V | tail -1)',
          '  if [ -n "$CANDIDATE" ] && [ -d "$CANDIDATE" ]; then',
          '    TOOL_PATH="$CANDIDATE"',
          '    TOOL_FOUND="sdkman"',
          '  fi',
          'fi',
        ].join('\n'),
      },
      {
        name: 'Homebrew OpenJDK',
        detect: [
          'REQUESTED="\\${{ inputs.java-version }}"',
          'BREW_JDK="/opt/homebrew/opt/openjdk@$REQUESTED"',
          '[ ! -d "$BREW_JDK" ] && BREW_JDK="/usr/local/opt/openjdk@$REQUESTED"',
          'if [ -d "$BREW_JDK" ]; then',
          '  if [ -d "$BREW_JDK/libexec/openjdk.jdk/Contents/Home" ]; then',
          '    TOOL_PATH="$BREW_JDK/libexec/openjdk.jdk/Contents/Home"',
          '  else',
          '    TOOL_PATH="$BREW_JDK"',
          '  fi',
          '  TOOL_FOUND="brew"',
          'fi',
        ].join('\n'),
      },
      {
        name: 'macOS JDK paths',
        detect: [
          'REQUESTED="\\${{ inputs.java-version }}"',
          'for JVM_DIR in /Library/Java/JavaVirtualMachines/*/Contents/Home; do',
          '  if [ -d "$JVM_DIR" ]; then',
          '    JVM_VER=$("$JVM_DIR/bin/java" -version 2>&1 | head -1 | sed \'s/.*"\\(.*\\)".*/\\1/\')',
          '    case "$JVM_VER" in',
          '      $REQUESTED*|*.$REQUESTED.*)',
          '        TOOL_PATH="$JVM_DIR"',
          '        TOOL_FOUND="system"',
          '        break',
          '        ;;',
          '    esac',
          '  fi',
          'done',
        ].join('\n'),
      },
      {
        name: 'existing JAVA_HOME',
        detect: [
          'if [ -n "$JAVA_HOME" ] && [ -x "$JAVA_HOME/bin/java" ]; then',
          '  TOOL_PATH="$JAVA_HOME"',
          '  TOOL_FOUND="existing"',
          'fi',
        ].join('\n'),
      },
      {
        name: 'java on PATH',
        detect: [
          'if command -v java &>/dev/null; then',
          '  JAVA_BIN=$(command -v java)',
          '  REAL_JAVA=$(readlink -f "$JAVA_BIN" 2>/dev/null || realpath "$JAVA_BIN" 2>/dev/null || echo "$JAVA_BIN")',
          '  CANDIDATE_HOME=$(dirname "$(dirname "$REAL_JAVA")")',
          '  if [ -x "$CANDIDATE_HOME/bin/java" ]; then',
          '    TOOL_PATH="$CANDIDATE_HOME"',
          '    TOOL_FOUND="path"',
          '  fi',
          'fi',
        ].join('\n'),
      },
    ],
    setup: [
      'FOUND_HOME="$TOOL_PATH"',
      'echo "Found Java via $TOOL_FOUND at $FOUND_HOME"',
      'export JAVA_HOME="$FOUND_HOME"',
      'echo "JAVA_HOME=$FOUND_HOME" >> $GITHUB_ENV',
      'echo "$FOUND_HOME/bin" >> $GITHUB_PATH',
      '',
      'JAVA_VER=$("$FOUND_HOME/bin/java" -version 2>&1 | head -1 | sed \'s/.*"\\(.*\\)".*/\\1/\')',
      'echo "java-version=$JAVA_VER" >> $GITHUB_OUTPUT',
      'echo "java-home=$FOUND_HOME" >> $GITHUB_OUTPUT',
      'echo "path=$FOUND_HOME/bin" >> $GITHUB_OUTPUT',
      'echo "Using Java $JAVA_VER from $FOUND_HOME"',
    ].join('\n'),
    notFoundMessage: [
      'Java $REQUESTED not found. Install with: brew install openjdk@$REQUESTED',
      '::error::Or via SDKMAN: sdk install java $REQUESTED-tem',
    ].join('\n'),
  },

  // ── Ruby ────────────────────────────────────────────────────────────────

  'actions/setup-ruby': {
    name: 'Setup Ruby (local shim)',
    description: 'Local runner shim — uses system Ruby',
    inputs: {
      'ruby-version': { description: 'Ruby version', default: 'default' },
      'bundler-cache': { description: 'Run bundle install and cache', default: 'false' },
      'bundler': { description: 'Bundler version', default: '' },
      'working-directory': { description: 'Working directory for bundle install', default: '.' },
      'cache-version': { description: 'Cache version key', default: '0' },
      'rubygems': { description: 'RubyGems version', default: '' },
    },
    outputs: {
      'ruby-version': { description: 'Installed Ruby version' },
      'ruby-prefix': { description: 'Ruby prefix path' },
    },
    detect: [
      {
        name: 'rbenv',
        detect: [
          'REQUESTED="\\${{ inputs.ruby-version }}"',
          'if command -v rbenv &>/dev/null; then',
          '  if [ "$REQUESTED" != "default" ]; then',
          '    AVAILABLE=$(rbenv versions --bare 2>/dev/null | grep "^$REQUESTED" | tail -1)',
          '    if [ -n "$AVAILABLE" ]; then',
          '      rbenv shell "$AVAILABLE" 2>/dev/null || rbenv local "$AVAILABLE" 2>/dev/null || true',
          '      TOOL_FOUND="rbenv"',
          '    fi',
          '  else',
          '    TOOL_FOUND="rbenv"',
          '  fi',
          'fi',
        ].join('\n'),
      },
      {
        name: 'rvm',
        detect: [
          'REQUESTED="\\${{ inputs.ruby-version }}"',
          'if command -v rvm &>/dev/null; then',
          '  if [ "$REQUESTED" != "default" ]; then',
          '    rvm use "$REQUESTED" 2>/dev/null && TOOL_FOUND="rvm" || true',
          '  else',
          '    TOOL_FOUND="rvm"',
          '  fi',
          'fi',
        ].join('\n'),
      },
      {
        name: 'system ruby',
        detect: [
          'if command -v ruby &>/dev/null; then',
          '  TOOL_FOUND="system"',
          'fi',
        ].join('\n'),
      },
    ],
    setup: [
      'RUBY_PATH=$(command -v ruby)',
      'RUBY_VER=$(ruby --version 2>&1 | awk \'{print $2}\')',
      'RUBY_PREFIX=$(ruby -e "puts RbConfig::CONFIG[\'prefix\']" 2>/dev/null || dirname "$(dirname "$RUBY_PATH")")',
      'echo "ruby-version=$RUBY_VER" >> $GITHUB_OUTPUT',
      'echo "ruby-prefix=$RUBY_PREFIX" >> $GITHUB_OUTPUT',
      'echo "Using Ruby $RUBY_VER ($TOOL_FOUND) at $RUBY_PATH"',
    ].join('\n'),
    notFoundMessage: 'Ruby not found. Install with: brew install rbenv && rbenv install $REQUESTED',
    additionalSteps: [
      '    - name: Setup Bundler',
      '      shell: bash',
      '      run: |',
      '        BUNDLER_CACHE="\\${{ inputs.bundler-cache }}"',
      '        WORK_DIR="\\${{ inputs.working-directory }}"',
      '        BUNDLER_VER="\\${{ inputs.bundler }}"',
      '        if [ "$BUNDLER_CACHE" = "true" ] && [ -f "$WORK_DIR/Gemfile" ]; then',
      '          echo "Running bundle install in $WORK_DIR..."',
      '          cd "$WORK_DIR"',
      '          if [ -n "$BUNDLER_VER" ]; then',
      '            gem install bundler -v "$BUNDLER_VER" 2>/dev/null || true',
      '          fi',
      '          bundle config set --local path vendor/bundle 2>/dev/null || true',
      '          bundle install --jobs 4 --retry 3',
      '        fi',
    ].join('\n'),
  },

  // ── Go ──────────────────────────────────────────────────────────────────

  'actions/setup-go': {
    name: 'Setup Go (local shim)',
    description: 'Local runner shim — uses system Go',
    inputs: {
      'go-version': { description: 'Go version', default: '' },
      'go-version-file': { description: 'Path to go.mod or go.work file', default: '' },
      'check-latest': { description: 'Check latest', default: 'false' },
      'token': { description: 'Token', default: '' },
      'cache': { description: 'Enable caching', default: 'true' },
      'cache-dependency-path': { description: 'Cache dependency path', default: '' },
      'architecture': { description: 'Architecture', default: '' },
    },
    outputs: {
      'go-version': { description: 'Installed Go version' },
      'cache-hit': { description: 'Cache hit' },
    },
    detect: [
      {
        name: 'goenv',
        detect: [
          'REQUESTED="\\${{ inputs.go-version }}"',
          'if command -v goenv &>/dev/null && [ -n "$REQUESTED" ]; then',
          '  AVAILABLE=$(goenv versions --bare 2>/dev/null | grep "^$REQUESTED" | tail -1)',
          '  if [ -n "$AVAILABLE" ]; then',
          '    goenv shell "$AVAILABLE" 2>/dev/null || goenv local "$AVAILABLE" 2>/dev/null || true',
          '    TOOL_FOUND="goenv"',
          '  fi',
          'fi',
        ].join('\n'),
      },
      {
        name: 'go on PATH',
        detect: [
          'if command -v go &>/dev/null; then',
          '  TOOL_FOUND="path"',
          'fi',
        ].join('\n'),
      },
      {
        name: 'Homebrew / common paths',
        detect: [
          'for GO_BIN in /opt/homebrew/bin/go /usr/local/bin/go /usr/local/go/bin/go; do',
          '  if [ -x "$GO_BIN" ]; then',
          '    echo "$(dirname "$GO_BIN")" >> $GITHUB_PATH',
          '    TOOL_FOUND="brew"',
          '    break',
          '  fi',
          'done',
        ].join('\n'),
      },
    ],
    setup: [
      'GO_BIN_PATH=$(command -v go)',
      'GO_VER=$(go version 2>&1 | awk \'{print $3}\' | sed \'s/^go//\')',
      '',
      '# Set GOPATH if not already set',
      'GOPATH_DIR="${GOPATH:-$HOME/go}"',
      'echo "GOPATH=$GOPATH_DIR" >> $GITHUB_ENV',
      'mkdir -p "$GOPATH_DIR/bin"',
      'echo "$GOPATH_DIR/bin" >> $GITHUB_PATH',
      '',
      'echo "go-version=$GO_VER" >> $GITHUB_OUTPUT',
      'echo "cache-hit=false" >> $GITHUB_OUTPUT',
      'echo "Using Go $GO_VER ($TOOL_FOUND) at $GO_BIN_PATH"',
    ].join('\n'),
    notFoundMessage: 'Go not found. Install with: brew install go',
  },

  // ── .NET ────────────────────────────────────────────────────────────────

  'actions/setup-dotnet': {
    name: 'Setup .NET (local shim)',
    description: 'Local runner shim — uses system .NET SDK',
    inputs: {
      'dotnet-version': { description: '.NET SDK version', default: '' },
      'dotnet-quality': { description: '.NET quality (daily, preview, ga)', default: '' },
      'global-json-file': { description: 'Path to global.json', default: '' },
      'source-url': { description: 'NuGet source URL', default: '' },
      'owner': { description: 'NuGet source owner', default: '' },
      'config-file': { description: 'NuGet config file', default: '' },
      'cache': { description: 'Enable caching', default: 'false' },
      'cache-dependency-path': { description: 'Cache dependency path', default: '' },
    },
    outputs: {
      'dotnet-version': { description: 'Installed .NET SDK version' },
      'cache-hit': { description: 'Cache hit' },
    },
    detect: [
      {
        name: 'dotnet on PATH',
        detect: [
          'if command -v dotnet &>/dev/null; then',
          '  TOOL_FOUND="path"',
          'fi',
        ].join('\n'),
      },
      {
        name: 'common install locations',
        detect: [
          'for DOTNET_BIN in "$HOME/.dotnet/dotnet" /usr/local/share/dotnet/dotnet /opt/homebrew/bin/dotnet; do',
          '  if [ -x "$DOTNET_BIN" ]; then',
          '    DOTNET_DIR=$(dirname "$DOTNET_BIN")',
          '    echo "$DOTNET_DIR" >> $GITHUB_PATH',
          '    export PATH="$DOTNET_DIR:$PATH"',
          '    TOOL_FOUND="system"',
          '    break',
          '  fi',
          'done',
        ].join('\n'),
      },
    ],
    setup: [
      'DOTNET_VER=$(dotnet --version 2>&1)',
      'echo "dotnet-version=$DOTNET_VER" >> $GITHUB_OUTPUT',
      'echo "cache-hit=false" >> $GITHUB_OUTPUT',
      '',
      '# Disable telemetry for CI',
      'echo "DOTNET_CLI_TELEMETRY_OPTOUT=1" >> $GITHUB_ENV',
      'echo "DOTNET_NOLOGO=1" >> $GITHUB_ENV',
      '',
      'echo "Using .NET SDK $DOTNET_VER"',
    ].join('\n'),
    notFoundMessage: [
      '.NET SDK not found. Install with: brew install dotnet-sdk',
      '::error::Or visit: https://dotnet.microsoft.com/download',
    ].join('\n'),
  },

  // ── Gradle ──────────────────────────────────────────────────────────────

  'actions/setup-gradle': {
    name: 'Setup Gradle (local shim)',
    description: 'Local runner shim — uses system Gradle or local wrapper',
    inputs: {
      'gradle-version': { description: 'Gradle version', default: '' },
      'cache-disabled': { description: 'Disable caching', default: 'false' },
      'cache-read-only': { description: 'Read-only cache', default: 'false' },
      'cache-write-only': { description: 'Write-only cache', default: 'false' },
      'gradle-home-cache-cleanup': { description: 'Cleanup Gradle home cache', default: 'false' },
      'build-root-directory': { description: 'Build root directory', default: '' },
      'arguments': { description: 'Gradle arguments', default: '' },
    },
    outputs: {
      'gradle-version': { description: 'Gradle version in use' },
    },
    detect: [
      {
        name: 'local Gradle wrapper (preferred for reproducibility)',
        detect: [
          'REQUESTED="\\${{ inputs.gradle-version }}"',
          'BUILD_ROOT="\\${{ inputs.build-root-directory }}"',
          'GRADLE_CMD=""',
          'WRAPPER_DIR="${BUILD_ROOT:-$GITHUB_WORKSPACE}"',
          'if [ -x "$WRAPPER_DIR/gradlew" ]; then',
          '  GRADLE_CMD="$WRAPPER_DIR/gradlew"',
          '  TOOL_PATH="$GRADLE_CMD"',
          '  TOOL_FOUND="wrapper"',
          'fi',
        ].join('\n'),
      },
      {
        name: 'gradle on PATH',
        detect: [
          'if command -v gradle &>/dev/null; then',
          '  GRADLE_CMD=$(command -v gradle)',
          '  TOOL_PATH="$GRADLE_CMD"',
          '  TOOL_FOUND="path"',
          'fi',
        ].join('\n'),
      },
      {
        name: 'Homebrew',
        detect: [
          'for GRADLE_BIN in /opt/homebrew/bin/gradle /usr/local/bin/gradle; do',
          '  if [ -x "$GRADLE_BIN" ]; then',
          '    GRADLE_CMD="$GRADLE_BIN"',
          '    TOOL_PATH="$GRADLE_CMD"',
          '    TOOL_FOUND="brew"',
          '    break',
          '  fi',
          'done',
        ].join('\n'),
      },
      {
        name: 'SDKMAN',
        detect: [
          'REQUESTED="\\${{ inputs.gradle-version }}"',
          'if [ -d "${SDKMAN_DIR:-$HOME/.sdkman}" ]; then',
          '  SDK_DIR="${SDKMAN_DIR:-$HOME/.sdkman}"',
          '  if [ -n "$REQUESTED" ]; then',
          '    CANDIDATE="$SDK_DIR/candidates/gradle/$REQUESTED/bin/gradle"',
          '  else',
          '    CANDIDATE=$(find "$SDK_DIR/candidates/gradle" -maxdepth 2 -name "gradle" -type f 2>/dev/null | sort -V | tail -1)',
          '  fi',
          '  if [ -n "$CANDIDATE" ] && [ -x "$CANDIDATE" ]; then',
          '    GRADLE_CMD="$CANDIDATE"',
          '    TOOL_PATH="$GRADLE_CMD"',
          '    echo "$(dirname "$CANDIDATE")" >> $GITHUB_PATH',
          '    TOOL_FOUND="sdkman"',
          '  fi',
          'fi',
        ].join('\n'),
      },
    ],
    softFail: true,
    setup: [
      'if [ -z "$TOOL_FOUND" ]; then',
      '  echo "gradle-version=none" >> $GITHUB_OUTPUT',
      '  exit 0',
      'fi',
      '',
      '# Set GRADLE_HOME for caching',
      'GRADLE_USER_HOME="${GRADLE_USER_HOME:-$HOME/.gradle}"',
      'echo "GRADLE_USER_HOME=$GRADLE_USER_HOME" >> $GITHUB_ENV',
      'mkdir -p "$GRADLE_USER_HOME"',
      '',
      'GRADLE_VER=$($GRADLE_CMD --version 2>/dev/null | grep "^Gradle " | awk \'{print $2}\' || echo "unknown")',
      'echo "gradle-version=$GRADLE_VER" >> $GITHUB_OUTPUT',
      'echo "Using Gradle $GRADLE_VER ($TOOL_FOUND) at $GRADLE_CMD"',
    ].join('\n'),
    notFoundMessage: [
      'Gradle not found. Install with: brew install gradle',
      '::warning::Or use a Gradle wrapper: gradle wrapper',
    ].join('\n'),
  },

  // ── Xcode ───────────────────────────────────────────────────────────────

  'actions/setup-xcode': {
    name: 'Setup Xcode (local shim)',
    description: 'Local runner shim — uses xcode-select',
    inputs: {
      'xcode-version': { description: 'Xcode version', default: 'latest-stable' },
    },
    outputs: {
      'xcode-version': { description: 'Selected Xcode version' },
      'xcode-path': { description: 'Path to selected Xcode' },
    },
    detect: [
      {
        name: 'xcode-select',
        detect: [
          'if ! command -v xcode-select &>/dev/null; then',
          '  echo "::error::xcode-select not found. This action requires macOS with Xcode installed."',
          '  exit 1',
          'fi',
          '',
          'REQUESTED="\\${{ inputs.xcode-version }}"',
          'XCODE_PATH=""',
          'XCODE_APP=""',
          '',
          'if [ "$REQUESTED" = "latest-stable" ] || [ "$REQUESTED" = "latest" ] || [ -z "$REQUESTED" ]; then',
          '  # Use whatever is currently selected, or find the latest installed',
          '  XCODE_PATH=$(xcode-select -p 2>/dev/null || true)',
          '  if [ -n "$XCODE_PATH" ]; then',
          '    # xcode-select -p returns .../Contents/Developer, go up to .app',
          '    XCODE_APP=$(echo "$XCODE_PATH" | sed \'s|/Contents/Developer.*||\')',
          '  fi',
          'else',
          '  # Try exact version match in /Applications',
          '  for APP in /Applications/Xcode_${REQUESTED}*.app /Applications/Xcode-${REQUESTED}*.app /Applications/Xcode${REQUESTED}*.app; do',
          '    if [ -d "$APP" ]; then',
          '      XCODE_APP="$APP"',
          '      XCODE_PATH="$APP/Contents/Developer"',
          '      break',
          '    fi',
          '  done',
          '',
          '  # Try without underscore (e.g., Xcode.app for default)',
          '  if [ -z "$XCODE_PATH" ] && [ -d "/Applications/Xcode.app" ]; then',
          '    XCODE_APP="/Applications/Xcode.app"',
          '    XCODE_PATH="/Applications/Xcode.app/Contents/Developer"',
          '  fi',
          '',
          '  if [ -n "$XCODE_PATH" ] && [ -d "$XCODE_PATH" ]; then',
          '    echo "Selecting Xcode at $XCODE_APP"',
          '    sudo xcode-select -s "$XCODE_PATH" 2>/dev/null || {',
          '      echo "::warning::Could not switch Xcode (sudo may be required). Using current selection."',
          '      XCODE_PATH=$(xcode-select -p 2>/dev/null || true)',
          '      XCODE_APP=$(echo "$XCODE_PATH" | sed \'s|/Contents/Developer.*||\')',
          '    }',
          '  fi',
          'fi',
          '',
          'if [ -n "$XCODE_PATH" ] && [ -d "$XCODE_PATH" ]; then',
          '  TOOL_PATH="$XCODE_PATH"',
          '  TOOL_FOUND="xcode-select"',
          'fi',
        ].join('\n'),
      },
    ],
    setup: [
      'XCODE_VER=$(xcodebuild -version 2>/dev/null | head -1 | awk \'{print $2}\' || echo "\\${{ inputs.xcode-version }}")',
      'echo "xcode-version=$XCODE_VER" >> $GITHUB_OUTPUT',
      'echo "xcode-path=$TOOL_PATH" >> $GITHUB_OUTPUT',
      'echo "DEVELOPER_DIR=$TOOL_PATH" >> $GITHUB_ENV',
      'echo "Using Xcode $XCODE_VER at $TOOL_PATH"',
    ].join('\n'),
    notFoundMessage: [
      'Xcode $REQUESTED not found in /Applications.',
      '::error::Available Xcode installations:',
    ].join('\n'),
  },

  // ── Flutter ─────────────────────────────────────────────────────────────

  'subosito/flutter-action': {
    name: 'Flutter Action (local shim)',
    description: 'Local runner shim — uses system Flutter',
    inputs: {
      'flutter-version': { description: 'Flutter version', default: '' },
      'channel': { description: 'Flutter channel (stable, beta, dev)', default: 'stable' },
      'cache': { description: 'Enable caching', default: 'false' },
      'cache-key': { description: 'Cache key prefix', default: '' },
      'cache-path': { description: 'Cache path', default: '' },
      'architecture': { description: 'Architecture', default: 'x64' },
    },
    outputs: {
      'flutter-version': { description: 'Installed Flutter version' },
      'dart-version': { description: 'Installed Dart version' },
      'cache-hit': { description: 'Cache hit' },
    },
    detect: [
      {
        name: 'flutter on PATH',
        detect: [
          'if command -v flutter &>/dev/null; then',
          '  TOOL_FOUND="path"',
          'fi',
        ].join('\n'),
      },
      {
        name: 'common install locations',
        detect: [
          'for FLUTTER_BIN in "$HOME/flutter/bin/flutter" "$HOME/.flutter/bin/flutter" \\',
          '                     /opt/homebrew/bin/flutter /usr/local/bin/flutter \\',
          '                     "$HOME/development/flutter/bin/flutter"; do',
          '  if [ -x "$FLUTTER_BIN" ]; then',
          '    FLUTTER_DIR=$(dirname "$FLUTTER_BIN")',
          '    echo "$FLUTTER_DIR" >> $GITHUB_PATH',
          '    export PATH="$FLUTTER_DIR:$PATH"',
          '    TOOL_FOUND="system"',
          '    break',
          '  fi',
          'done',
        ].join('\n'),
      },
      {
        name: 'fvm (Flutter Version Management)',
        detect: [
          'if command -v fvm &>/dev/null; then',
          '  CHANNEL="\\${{ inputs.channel }}"',
          '  FVM_FLUTTER=$(fvm which flutter 2>/dev/null || true)',
          '  if [ -n "$FVM_FLUTTER" ] && [ -x "$FVM_FLUTTER" ]; then',
          '    echo "$(dirname "$FVM_FLUTTER")" >> $GITHUB_PATH',
          '    export PATH="$(dirname "$FVM_FLUTTER"):$PATH"',
          '    TOOL_FOUND="fvm"',
          '  fi',
          'fi',
        ].join('\n'),
      },
    ],
    setup: [
      'FLUTTER_VER=$(flutter --version --machine 2>/dev/null | grep \'"frameworkVersion"\' | sed \'s/.*: "\\(.*\\)".*/\\1/\' || flutter --version 2>&1 | head -1 | awk \'{print $2}\')',
      'DART_VER=$(dart --version 2>&1 | awk \'{print $4}\' || echo "unknown")',
      '',
      '# Accept licenses non-interactively',
      'flutter config --no-analytics 2>/dev/null || true',
      'dart --disable-analytics 2>/dev/null || true',
      '',
      '# Ensure flutter is on the right channel',
      'CHANNEL="\\${{ inputs.channel }}"',
      'if [ -n "$CHANNEL" ] && [ "$CHANNEL" != "stable" ]; then',
      '  echo "Requested channel: $CHANNEL (switching is skipped for local shim)"',
      'fi',
      '',
      'echo "flutter-version=$FLUTTER_VER" >> $GITHUB_OUTPUT',
      'echo "dart-version=$DART_VER" >> $GITHUB_OUTPUT',
      'echo "cache-hit=false" >> $GITHUB_OUTPUT',
      'echo "Using Flutter $FLUTTER_VER with Dart $DART_VER"',
    ].join('\n'),
    notFoundMessage: [
      'Flutter not found. Install with: brew install --cask flutter',
      '::error::Or visit: https://docs.flutter.dev/get-started/install',
    ].join('\n'),
  },

};
