import type {
  WorkflowRun,
  Feature,
  PullRequest,
  ActivityItem,
  Artifact,
  FeatureWithDiffs,
  DiffVersionInfo,
} from "./types";

export const mockWorkflowRuns: WorkflowRun[] = [
  {
    id: "run-001",
    workflow: "CI Pipeline",
    status: "completed",
    conclusion: "success",
    createdAt: "2026-03-21T14:30:00Z",
    updatedAt: "2026-03-21T14:45:00Z",
    trigger: { event: "push", ref: "refs/heads/main", sha: "a1b2c3d" },
    jobs: [
      {
        id: "job-001",
        name: "Build & Test",
        status: "completed",
        conclusion: "success",
        startedAt: "2026-03-21T14:30:15Z",
        completedAt: "2026-03-21T14:42:30Z",
        steps: [
          {
            name: "Checkout code",
            status: "completed",
            conclusion: "success",
            log: "Cloning repository...\nFetching refs/heads/main\nChecked out a1b2c3d",
          },
          {
            name: "Install dependencies",
            status: "completed",
            conclusion: "success",
            log: "npm ci\nadded 1247 packages in 28s\n\n142 packages are looking for funding\n  run `npm fund` for details",
          },
          {
            name: "Run linter",
            status: "completed",
            conclusion: "success",
            log: "Running ESLint...\n\n✓ No issues found\n\n247 files checked",
          },
          {
            name: "Run tests",
            status: "completed",
            conclusion: "success",
            log: "PASS src/lib/utils.test.ts\nPASS src/components/Button.test.tsx\nPASS src/hooks/useAuth.test.ts\nPASS src/api/features.test.ts\n\nTest Suites: 4 passed, 4 total\nTests:       23 passed, 23 total\nTime:        4.821s",
          },
          {
            name: "Build",
            status: "completed",
            conclusion: "success",
            log: "Creating optimized production build...\n\n✓ Compiled successfully\n\nRoute (app)           Size     First Load JS\n├ /                   5.2 kB   89 kB\n├ /features           3.1 kB   87 kB\n├ /prs                4.8 kB   88 kB\n└ /runs               3.6 kB   87 kB\n\n✓ Build completed in 12.4s",
          },
        ],
      },
      {
        id: "job-002",
        name: "Deploy Preview",
        status: "completed",
        conclusion: "success",
        startedAt: "2026-03-21T14:42:35Z",
        completedAt: "2026-03-21T14:45:00Z",
        steps: [
          {
            name: "Deploy to preview",
            status: "completed",
            conclusion: "success",
            log: "Deploying to preview environment...\nUpload complete\nPreview URL: https://preview-a1b2c3d.example.com\n\n✓ Deployment successful",
          },
        ],
      },
    ],
  },
  {
    id: "run-002",
    workflow: "Integration Tests",
    status: "completed",
    conclusion: "failure",
    createdAt: "2026-03-21T10:15:00Z",
    updatedAt: "2026-03-21T10:35:00Z",
    trigger: {
      event: "pull_request",
      ref: "refs/heads/feat/gpu-inference",
      sha: "e5f6g7h",
    },
    jobs: [
      {
        id: "job-003",
        name: "Integration Suite",
        status: "completed",
        conclusion: "failure",
        startedAt: "2026-03-21T10:15:30Z",
        completedAt: "2026-03-21T10:35:00Z",
        steps: [
          {
            name: "Setup environment",
            status: "completed",
            conclusion: "success",
            log: "Setting up test environment...\nPulling Docker images...\nStarting services...\n\n✓ Environment ready",
          },
          {
            name: "Run integration tests",
            status: "completed",
            conclusion: "failure",
            log: 'PASS tests/api/auth.test.ts\nPASS tests/api/features.test.ts\nFAIL tests/api/inference.test.ts\n  ● GPU inference endpoint › should return embeddings\n    Expected: 768 dimensions\n    Received: undefined\n\n    Error: Connection refused at localhost:8080\n      at Object.<anonymous> (tests/api/inference.test.ts:42:5)\n\nTest Suites: 1 failed, 2 passed, 3 total\nTests:       1 failed, 11 passed, 12 total\nTime:        18.234s',
          },
        ],
      },
    ],
  },
  {
    id: "run-003",
    workflow: "CI Pipeline",
    status: "in_progress",
    createdAt: "2026-03-22T08:00:00Z",
    updatedAt: "2026-03-22T08:05:00Z",
    trigger: {
      event: "push",
      ref: "refs/heads/feat/embeddings-api",
      sha: "i9j0k1l",
    },
    jobs: [
      {
        id: "job-004",
        name: "Build & Test",
        status: "in_progress",
        startedAt: "2026-03-22T08:00:15Z",
        steps: [
          {
            name: "Checkout code",
            status: "completed",
            conclusion: "success",
            log: "Cloning repository...\nChecked out i9j0k1l",
          },
          {
            name: "Install dependencies",
            status: "completed",
            conclusion: "success",
            log: "npm ci\nadded 1247 packages in 26s",
          },
          {
            name: "Run linter",
            status: "in_progress",
            log: "Running ESLint...\nChecking files...",
          },
          {
            name: "Run tests",
            status: "queued",
            log: "",
          },
          {
            name: "Build",
            status: "queued",
            log: "",
          },
        ],
      },
    ],
  },
  {
    id: "run-004",
    workflow: "Deploy Production",
    status: "completed",
    conclusion: "success",
    createdAt: "2026-03-20T16:00:00Z",
    updatedAt: "2026-03-20T16:12:00Z",
    trigger: { event: "push", ref: "refs/heads/main", sha: "m2n3o4p" },
    jobs: [
      {
        id: "job-005",
        name: "Deploy",
        status: "completed",
        conclusion: "success",
        startedAt: "2026-03-20T16:00:10Z",
        completedAt: "2026-03-20T16:12:00Z",
        steps: [
          {
            name: "Build image",
            status: "completed",
            conclusion: "success",
            log: "Building Docker image...\nStep 1/12 : FROM node:20-alpine\nStep 2/12 : WORKDIR /app\n...\nSuccessfully built abc123def\nSuccessfully tagged devpod/platform:latest",
          },
          {
            name: "Push to registry",
            status: "completed",
            conclusion: "success",
            log: "Pushing devpod/platform:latest...\nsha256:abc123def: Pushed\nlatest: digest: sha256:abc123def size: 3048",
          },
          {
            name: "Rolling deploy",
            status: "completed",
            conclusion: "success",
            log: 'Updating deployment...\nWaiting for rollout...\ndeployment "platform" successfully rolled out\n\n✓ Production deployment complete',
          },
        ],
      },
    ],
  },
  {
    id: "run-005",
    workflow: "Nightly Data Sync",
    status: "completed",
    conclusion: "success",
    createdAt: "2026-03-22T02:00:00Z",
    updatedAt: "2026-03-22T02:15:00Z",
    trigger: { event: "schedule", ref: "refs/heads/main", sha: "q5r6s7t" },
    jobs: [
      {
        id: "job-006",
        name: "Sync Data",
        status: "completed",
        conclusion: "success",
        startedAt: "2026-03-22T02:00:05Z",
        completedAt: "2026-03-22T02:15:00Z",
        steps: [
          {
            name: "Fetch upstream data",
            status: "completed",
            conclusion: "success",
            log: "Fetching data from upstream sources...\nDownloaded 2.4 GB in 180s\n\n✓ Data fetch complete",
          },
          {
            name: "Transform and validate",
            status: "completed",
            conclusion: "success",
            log: "Running transformations...\nValidating 1,247,832 records...\n0 validation errors\n\n✓ All records valid",
          },
          {
            name: "Upload to storage",
            status: "completed",
            conclusion: "success",
            log: "Uploading to object storage...\nUploaded 2.4 GB\n\n✓ Sync complete",
          },
        ],
      },
    ],
  },
  {
    id: "run-006",
    workflow: "CI Pipeline",
    status: "queued",
    createdAt: "2026-03-22T09:00:00Z",
    updatedAt: "2026-03-22T09:00:00Z",
    trigger: {
      event: "pull_request",
      ref: "refs/heads/fix/auth-token-refresh",
      sha: "u8v9w0x",
    },
    jobs: [
      {
        id: "job-007",
        name: "Build & Test",
        status: "queued",
        steps: [
          { name: "Checkout code", status: "queued", log: "" },
          { name: "Install dependencies", status: "queued", log: "" },
          { name: "Run linter", status: "queued", log: "" },
          { name: "Run tests", status: "queued", log: "" },
          { name: "Build", status: "queued", log: "" },
        ],
      },
    ],
  },
];

export const mockFeatures: Feature[] = [
  {
    slug: "gpu-inference-engine",
    title: "GPU Inference Engine",
    description:
      "High-performance GPU-accelerated inference engine supporting multiple model architectures including transformer-based LLMs. Includes automatic batching, dynamic memory management, and quantization support for optimal throughput on RunPod infrastructure.",
    date: "2026-03-18",
    status: "shipped",
    video: "/videos/gpu-inference-demo.mp4",
    screenshots: [
      "/screenshots/inference-dashboard.png",
      "/screenshots/inference-metrics.png",
      "/screenshots/inference-config.png",
    ],
    prs: [
      {
        number: 42,
        title: "Add GPU inference engine core",
        repo: "devpod",
        status: "merged",
      },
      {
        number: 45,
        title: "Add batching support for inference",
        repo: "devpod",
        status: "merged",
      },
      {
        number: 48,
        title: "Add quantization support (INT8/FP16)",
        repo: "devpod",
        status: "merged",
      },
    ],
  },
  {
    slug: "embeddings-api",
    title: "Embeddings API",
    description:
      "REST API for generating vector embeddings from text and code using GPU-accelerated models. Supports batch processing, multiple embedding models, and automatic dimensionality selection. Integrates with the existing inference engine for shared GPU resource management.",
    date: "2026-03-21",
    status: "review",
    video: "/videos/embeddings-demo.mp4",
    screenshots: [
      "/screenshots/embeddings-playground.png",
      "/screenshots/embeddings-docs.png",
    ],
    prs: [
      {
        number: 51,
        title: "Add embeddings API endpoint",
        repo: "devpod",
        status: "open",
      },
      {
        number: 53,
        title: "Add batch embedding support",
        repo: "devpod",
        status: "open",
      },
    ],
  },
  {
    slug: "synthetic-data-pipeline",
    title: "Synthetic Data Generation Pipeline",
    description:
      "End-to-end pipeline for generating high-quality synthetic training data using LLMs. Includes configurable generation templates, quality scoring, deduplication, and export in multiple formats (JSONL, Parquet, HuggingFace datasets).",
    date: "2026-03-22",
    status: "in-progress",
    screenshots: ["/screenshots/datagen-config.png"],
    prs: [
      {
        number: 55,
        title: "Add synthetic data generation skill",
        repo: "devpod",
        status: "open",
      },
    ],
  },
  {
    slug: "workflow-runner",
    title: "Local Workflow Runner",
    description:
      "GitHub Actions-compatible workflow runner that executes CI/CD pipelines locally. Supports Docker-based job execution, artifact management, and real-time log streaming via Server-Sent Events.",
    date: "2026-03-15",
    status: "shipped",
    video: "/videos/runner-demo.mp4",
    screenshots: [
      "/screenshots/runner-logs.png",
      "/screenshots/runner-artifacts.png",
      "/screenshots/runner-config.png",
    ],
    prs: [
      {
        number: 30,
        title: "Add local workflow runner",
        repo: "devpod",
        status: "merged",
      },
      {
        number: 33,
        title: "Add SSE log streaming",
        repo: "devpod",
        status: "merged",
      },
      {
        number: 36,
        title: "Add artifact upload/download",
        repo: "devpod",
        status: "merged",
      },
    ],
  },
  {
    slug: "auth-rbac",
    title: "Authentication & RBAC",
    description:
      "Token-based authentication system with role-based access control. Supports API keys, JWT tokens, and granular permissions for managing access to inference endpoints, data pipelines, and administrative functions.",
    date: "2026-03-12",
    status: "shipped",
    screenshots: [
      "/screenshots/auth-login.png",
      "/screenshots/auth-roles.png",
    ],
    prs: [
      {
        number: 22,
        title: "Add JWT authentication",
        repo: "devpod",
        status: "merged",
      },
      {
        number: 25,
        title: "Add role-based access control",
        repo: "devpod",
        status: "merged",
      },
    ],
  },
];

export const mockPullRequests: PullRequest[] = [
  {
    sha: "mock55000000000000000000000000000000000055",
    shortSha: "mock55",
    title: "Add synthetic data generation skill",
    body: "Adds a new Claude Code skill for generating synthetic training data using LLMs.",
    author: "arun",
    date: "2026-03-22T07:30:00Z",
    parentSha: "mock53000000000000000000000000000000000053",
    files: [
      { path: "skills/datagen/index.ts", status: "added", additions: 45, deletions: 0, isGenerated: false, diff: "" },
      { path: "skills/datagen/generator.ts", status: "added", additions: 32, deletions: 0, isGenerated: false, diff: "" },
    ],
    totalAdditions: 213,
    totalDeletions: 0,
    number: 55,
    branch: "feat/synthetic-datagen",
    baseBranch: "main",
    status: "open",
    feature: "synthetic-data-pipeline",
    createdAt: "2026-03-22T07:30:00Z",
    checks: [mockWorkflowRuns[2]],
  },
  {
    sha: "mock53000000000000000000000000000000000053",
    shortSha: "mock53",
    title: "Add batch embedding support",
    body: "Adds batch processing support to the embeddings API.",
    author: "arun",
    date: "2026-03-21T15:00:00Z",
    parentSha: "mock51000000000000000000000000000000000051",
    files: [
      { path: "api/embeddings/batch.ts", status: "added", additions: 38, deletions: 0, isGenerated: false, diff: "" },
    ],
    totalAdditions: 104,
    totalDeletions: 3,
    number: 53,
    branch: "feat/batch-embeddings",
    baseBranch: "main",
    status: "open",
    feature: "embeddings-api",
    createdAt: "2026-03-21T15:00:00Z",
    checks: [mockWorkflowRuns[1]],
  },
  {
    sha: "mock51000000000000000000000000000000000051",
    shortSha: "mock51",
    title: "Add embeddings API endpoint",
    body: "Adds the core embeddings API endpoint for generating vector embeddings.",
    author: "arun",
    date: "2026-03-20T11:00:00Z",
    parentSha: "mock48000000000000000000000000000000000048",
    files: [
      { path: "api/embeddings/index.ts", status: "added", additions: 42, deletions: 0, isGenerated: false, diff: "" },
    ],
    totalAdditions: 145,
    totalDeletions: 0,
    number: 51,
    branch: "feat/embeddings-api",
    baseBranch: "main",
    status: "open",
    feature: "embeddings-api",
    createdAt: "2026-03-20T11:00:00Z",
    checks: [mockWorkflowRuns[0]],
  },
  {
    sha: "mock48000000000000000000000000000000000048",
    shortSha: "mock48",
    title: "Add quantization support (INT8/FP16)",
    body: "Adds model quantization support for the GPU inference engine.",
    author: "arun",
    date: "2026-03-17T09:00:00Z",
    parentSha: "mock45000000000000000000000000000000000045",
    files: [
      { path: "inference/quantize.ts", status: "added", additions: 28, deletions: 0, isGenerated: false, diff: "" },
    ],
    totalAdditions: 85,
    totalDeletions: 4,
    number: 48,
    branch: "feat/quantization",
    baseBranch: "main",
    status: "merged",
    feature: "gpu-inference-engine",
    createdAt: "2026-03-17T09:00:00Z",
    checks: [{ ...mockWorkflowRuns[0], id: "run-010", createdAt: "2026-03-17T09:05:00Z" }],
  },
  {
    sha: "mock45000000000000000000000000000000000045",
    shortSha: "mock45",
    title: "Add batching support for inference",
    body: "Implements automatic request batching for the inference engine.",
    author: "arun",
    date: "2026-03-16T14:00:00Z",
    parentSha: "mock42000000000000000000000000000000000042",
    files: [
      { path: "inference/batcher.ts", status: "added", additions: 68, deletions: 0, isGenerated: false, diff: "" },
    ],
    totalAdditions: 90,
    totalDeletions: 8,
    number: 45,
    branch: "feat/inference-batching",
    baseBranch: "main",
    status: "merged",
    feature: "gpu-inference-engine",
    createdAt: "2026-03-16T14:00:00Z",
    checks: [{ ...mockWorkflowRuns[0], id: "run-011", createdAt: "2026-03-16T14:05:00Z" }],
  },
  {
    sha: "mock42000000000000000000000000000000000042",
    shortSha: "mock42",
    title: "Add GPU inference engine core",
    body: "Adds the core GPU inference engine with support for transformer-based model loading.",
    author: "arun",
    date: "2026-03-14T10:00:00Z",
    parentSha: "",
    files: [
      { path: "inference/engine.ts", status: "added", additions: 120, deletions: 0, isGenerated: false, diff: "" },
    ],
    totalAdditions: 237,
    totalDeletions: 0,
    number: 42,
    branch: "feat/gpu-inference",
    baseBranch: "main",
    status: "merged",
    feature: "gpu-inference-engine",
    createdAt: "2026-03-14T10:00:00Z",
    checks: [{ ...mockWorkflowRuns[0], id: "run-012", createdAt: "2026-03-14T10:05:00Z" }],
  },
];

export const mockArtifacts: Record<string, Artifact[]> = {
  "run-001": [
    {
      id: "art-001",
      name: "build-output.tar.gz",
      path: "artifacts/build-output.tar.gz",
      size: 15728640,
      mimeType: "application/gzip",
    },
    {
      id: "art-002",
      name: "test-report.html",
      path: "artifacts/test-report.html",
      size: 245760,
      mimeType: "text/html",
    },
    {
      id: "art-003",
      name: "coverage-report.json",
      path: "artifacts/coverage-report.json",
      size: 102400,
      mimeType: "application/json",
    },
  ],
  "run-004": [
    {
      id: "art-004",
      name: "docker-image-manifest.json",
      path: "artifacts/docker-image-manifest.json",
      size: 4096,
      mimeType: "application/json",
    },
  ],
};

export const mockActivity: ActivityItem[] = [
  {
    id: "act-1",
    type: "run",
    title: "CI Pipeline started",
    description: "Push to feat/embeddings-api triggered CI Pipeline",
    status: "in_progress",
    date: "2026-03-22T08:00:00Z",
    link: "/runs/run-003",
  },
  {
    id: "act-2",
    type: "pr",
    title: "PR #55 opened",
    description: "Add synthetic data generation skill",
    status: "open",
    date: "2026-03-22T07:30:00Z",
    link: "/prs/55",
  },
  {
    id: "act-3",
    type: "feature",
    title: "Embeddings API moved to review",
    description: "Embeddings API is now in review status",
    status: "review",
    date: "2026-03-21T15:00:00Z",
    link: "/features/embeddings-api",
  },
  {
    id: "act-4",
    type: "run",
    title: "Integration Tests failed",
    description: "Tests failed for feat/gpu-inference",
    status: "failed",
    date: "2026-03-21T10:35:00Z",
    link: "/runs/run-002",
  },
  {
    id: "act-5",
    type: "run",
    title: "CI Pipeline completed",
    description: "All checks passed for push to main",
    status: "completed",
    date: "2026-03-21T14:45:00Z",
    link: "/runs/run-001",
  },
  {
    id: "act-6",
    type: "feature",
    title: "GPU Inference Engine shipped",
    description: "GPU Inference Engine is now marked as shipped",
    status: "shipped",
    date: "2026-03-18T12:00:00Z",
    link: "/features/gpu-inference-engine",
  },
  {
    id: "act-7",
    type: "pr",
    title: "PR #48 merged",
    description: "Add quantization support (INT8/FP16)",
    status: "merged",
    date: "2026-03-17T18:00:00Z",
    link: "/prs/48",
  },
  {
    id: "act-8",
    type: "run",
    title: "Deploy Production completed",
    description: "Production deployment successful",
    status: "completed",
    date: "2026-03-20T16:12:00Z",
    link: "/runs/run-004",
  },
];

export const mockStackedDiffs: FeatureWithDiffs[] = [
  {
    feature: {
      name: "user authentication",
      type: "feature",
      slug: "user-authentication",
      branch: "feature/user-authentication",
      created: "2026-03-28T10:45:00Z",
      status: "active",
    },
    diffs: [
      {
        uuid: "d-auth-001",
        position: 1,
        title: "feat(auth): add API endpoints",
        description:
          "- Add /api/auth/login and /api/auth/register\n- JWT token generation\n- Password hashing with bcrypt",
        type: "feature",
        status: "approved",
        ci: "passed",
        commit: "abc1234",
        files: [
          { path: "src/api/auth/login.ts", status: "added", additions: 85, deletions: 0, isGenerated: false, diff: "diff --git a/src/api/auth/login.ts b/src/api/auth/login.ts\nnew file mode 100644\n--- /dev/null\n+++ b/src/api/auth/login.ts\n@@ -0,0 +1,85 @@\n+import { Router } from 'express';\n+import { hash, compare } from 'bcrypt';\n+import { sign } from 'jsonwebtoken';\n+import { db } from '../db';\n+\n+const router = Router();\n+\n+router.post('/login', async (req, res) => {\n+  const { email, password } = req.body;\n+\n+  if (!email || !password) {\n+    return res.status(400).json({ error: 'Email and password required' });\n+  }\n+\n+  const user = await db.users.findByEmail(email);\n+  if (!user) {\n+    return res.status(401).json({ error: 'Invalid credentials' });\n+  }\n+\n+  const valid = await compare(password, user.passwordHash);\n+  if (!valid) {\n+    return res.status(401).json({ error: 'Invalid credentials' });\n+  }\n+\n+  const token = sign({ userId: user.id, role: user.role }, process.env.JWT_SECRET!, {\n+    expiresIn: '24h',\n+  });\n+\n+  res.json({ token, user: { id: user.id, email: user.email, role: user.role } });\n+});\n+\n+export default router;" },
          { path: "src/api/auth/register.ts", status: "added", additions: 65, deletions: 0, isGenerated: false, diff: "diff --git a/src/api/auth/register.ts b/src/api/auth/register.ts\nnew file mode 100644\n--- /dev/null\n+++ b/src/api/auth/register.ts\n@@ -0,0 +1,65 @@\n+import { Router } from 'express';\n+import { hash } from 'bcrypt';\n+import { db } from '../db';\n+\n+const router = Router();\n+\n+router.post('/register', async (req, res) => {\n+  const { email, password, name } = req.body;\n+\n+  if (!email || !password || !name) {\n+    return res.status(400).json({ error: 'All fields required' });\n+  }\n+\n+  const existing = await db.users.findByEmail(email);\n+  if (existing) {\n+    return res.status(409).json({ error: 'Email already registered' });\n+  }\n+\n+  const passwordHash = await hash(password, 12);\n+  const user = await db.users.create({ email, passwordHash, name });\n+\n+  res.status(201).json({ user: { id: user.id, email: user.email } });\n+});\n+\n+export default router;" },
          { path: "src/middleware/auth.ts", status: "added", additions: 50, deletions: 5, isGenerated: false, diff: "diff --git a/src/middleware/auth.ts b/src/middleware/auth.ts\nnew file mode 100644\n--- /dev/null\n+++ b/src/middleware/auth.ts\n@@ -0,0 +1,50 @@\n+import { verify } from 'jsonwebtoken';\n+import type { Request, Response, NextFunction } from 'express';\n+\n+export function requireAuth(req: Request, res: Response, next: NextFunction) {\n+  const header = req.headers.authorization;\n+  if (!header?.startsWith('Bearer ')) {\n+    return res.status(401).json({ error: 'No token provided' });\n+  }\n+\n+  try {\n+    const token = header.slice(7);\n+    const payload = verify(token, process.env.JWT_SECRET!);\n+    req.user = payload as { userId: string; role: string };\n+    next();\n+  } catch {\n+    return res.status(401).json({ error: 'Invalid token' });\n+  }\n+}" },
        ],
        additions: 200,
        deletions: 5,
        version: 2,
        created: "2026-03-28T10:45:00Z",
        updated: "2026-03-29T14:20:00Z",
      },
      {
        uuid: "d-auth-002",
        position: 2,
        title: "feat(auth): add login form",
        description:
          "- Email/password form with client-side validation\n- Error display for failed login attempts\n- Remember me checkbox with token persistence",
        type: "feature",
        status: "submitted",
        ci: "passed",
        commit: "def5678",
        files: [
          { path: "src/components/auth/LoginForm.tsx", status: "added", additions: 180, deletions: 0, isGenerated: false, diff: "diff --git a/src/components/auth/LoginForm.tsx b/src/components/auth/LoginForm.tsx\nnew file mode 100644\n--- /dev/null\n+++ b/src/components/auth/LoginForm.tsx\n@@ -0,0 +1,180 @@\n+import { useState } from 'react';\n+\n+export function LoginForm() {\n+  const [email, setEmail] = useState('');\n+  const [password, setPassword] = useState('');\n+  const [error, setError] = useState('');\n+  const [loading, setLoading] = useState(false);\n+\n+  const handleSubmit = async (e: React.FormEvent) => {\n+    e.preventDefault();\n+    setLoading(true);\n+    setError('');\n+\n+    try {\n+      const res = await fetch('/api/auth/login', {\n+        method: 'POST',\n+        headers: { 'Content-Type': 'application/json' },\n+        body: JSON.stringify({ email, password }),\n+      });\n+\n+      if (!res.ok) throw new Error('Invalid credentials');\n+      const { token } = await res.json();\n+      localStorage.setItem('token', token);\n+      window.location.href = '/dashboard';\n+    } catch (err) {\n+      setError(err instanceof Error ? err.message : 'Login failed');\n+    } finally {\n+      setLoading(false);\n+    }\n+  };\n+\n+  return (\n+    <form onSubmit={handleSubmit}>\n+      <input type=\"email\" value={email} onChange={e => setEmail(e.target.value)} />\n+      <input type=\"password\" value={password} onChange={e => setPassword(e.target.value)} />\n+      {error && <p className=\"error\">{error}</p>}\n+      <button type=\"submit\" disabled={loading}>{loading ? 'Signing in...' : 'Sign In'}</button>\n+    </form>\n+  );\n+}" },
          { path: "src/components/auth/RegisterForm.tsx", status: "added", additions: 120, deletions: 0, isGenerated: false, diff: "" },
          { path: "src/hooks/useAuth.ts", status: "added", additions: 60, deletions: 0, isGenerated: false, diff: "" },
          { path: "src/lib/validators.ts", status: "modified", additions: 30, deletions: 5, isGenerated: false, diff: "" },
          { path: "src/styles/auth.css", status: "added", additions: 10, deletions: 5, isGenerated: false, diff: "" },
        ],
        additions: 400,
        deletions: 10,
        version: 1,
        created: "2026-03-29T09:00:00Z",
        updated: "2026-03-30T11:30:00Z",
      },
      {
        uuid: "d-auth-003",
        position: 3,
        title: "feat(auth): add E2E tests",
        description:
          "- Playwright tests for login flow\n- Tests for registration validation\n- Session persistence tests",
        type: "feature",
        status: "draft",
        ci: null,
        commit: "ghi9012",
        files: [
          { path: "tests/e2e/auth/login.spec.ts", status: "added", additions: 95, deletions: 0, isGenerated: false, diff: "" },
          { path: "tests/e2e/auth/register.spec.ts", status: "added", additions: 55, deletions: 0, isGenerated: false, diff: "" },
        ],
        additions: 150,
        deletions: 0,
        version: 1,
        created: "2026-03-30T14:00:00Z",
        updated: "2026-03-30T14:00:00Z",
      },
    ],
    isCurrent: true,
  },
  {
    feature: {
      name: "search redesign",
      type: "feature",
      slug: "search-redesign",
      branch: "feature/search-redesign",
      created: "2026-03-30T08:00:00Z",
      status: "active",
    },
    diffs: [
      {
        uuid: "d-search-001",
        position: 1,
        title: "feat(search): add fuzzy matching",
        description:
          "- Implement Levenshtein distance scoring\n- Add result ranking by relevance",
        type: "feature",
        status: "draft",
        ci: null,
        commit: "jkl3456",
        files: [
          { path: "src/lib/search/fuzzy.ts", status: "added", additions: 55, deletions: 0, isGenerated: false, diff: "" },
          { path: "src/lib/search/index.ts", status: "modified", additions: 25, deletions: 20, isGenerated: false, diff: "" },
        ],
        additions: 80,
        deletions: 20,
        version: 1,
        created: "2026-03-30T08:15:00Z",
        updated: "2026-03-30T08:15:00Z",
      },
    ],
    isCurrent: false,
  },
  {
    feature: {
      name: "fix token refresh",
      type: "fix",
      slug: "fix-token-refresh",
      branch: "fix/token-refresh",
      created: "2026-03-27T16:00:00Z",
      status: "submitted",
    },
    diffs: [
      {
        uuid: "d-fix-001",
        position: 1,
        title: "fix(auth): handle expired refresh tokens",
        description:
          "- Catch token expiry errors in middleware\n- Redirect to login on refresh failure\n- Clear stale tokens from localStorage",
        type: "fix",
        status: "approved",
        ci: "passed",
        commit: "mno7890",
        files: [
          { path: "src/middleware/auth.ts", status: "modified", additions: 25, deletions: 8, isGenerated: false, diff: "" },
          { path: "src/lib/token.ts", status: "modified", additions: 15, deletions: 3, isGenerated: false, diff: "" },
        ],
        additions: 40,
        deletions: 11,
        version: 3,
        created: "2026-03-27T16:15:00Z",
        updated: "2026-03-29T10:00:00Z",
      },
      {
        uuid: "d-fix-002",
        position: 2,
        title: "fix(auth): add refresh token rotation",
        description:
          "- Implement token rotation on refresh\n- Invalidate old refresh tokens",
        type: "fix",
        status: "submitted",
        ci: "failed",
        commit: "pqr1234",
        files: [
          { path: "src/api/auth/refresh.ts", status: "added", additions: 45, deletions: 0, isGenerated: false, diff: "" },
          { path: "src/db/migrations/add-token-rotation.ts", status: "added", additions: 20, deletions: 0, isGenerated: false, diff: "" },
        ],
        additions: 65,
        deletions: 0,
        version: 1,
        created: "2026-03-28T09:00:00Z",
        updated: "2026-03-29T11:00:00Z",
      },
    ],
    isCurrent: false,
  },
  {
    feature: {
      name: "update API docs",
      type: "docs",
      slug: "update-api-docs",
      branch: "docs/api-docs",
      created: "2026-03-25T10:00:00Z",
      status: "complete",
    },
    diffs: [
      {
        uuid: "d-docs-001",
        position: 1,
        title: "docs: update authentication API reference",
        description: "- Updated OpenAPI spec for auth endpoints\n- Added example requests/responses",
        type: "docs",
        status: "landed",
        ci: "passed",
        commit: "stu5678",
        files: [
          { path: "docs/api/auth.md", status: "modified", additions: 120, deletions: 45, isGenerated: false, diff: "" },
          { path: "docs/openapi.yaml", status: "modified", additions: 80, deletions: 30, isGenerated: false, diff: "" },
        ],
        additions: 200,
        deletions: 75,
        version: 2,
        created: "2026-03-25T10:30:00Z",
        updated: "2026-03-26T09:00:00Z",
      },
    ],
    isCurrent: false,
  },
];

// ─── Mock Version Histories ────────────────────────────────
// Keyed by "slug/position"

export const mockVersionHistories: Record<string, DiffVersionInfo[]> = {
  "user-authentication/1": [
    {
      snapshotId: "S1",
      snapshotSha: "abc001abc001abc001abc001abc001abc001abc0",
      version: 1,
      action: "create",
      message: "add auth API endpoints",
      date: "2026-03-28T10:45:00Z",
      stack: "D1v1",
    },
    {
      snapshotId: "S4",
      snapshotSha: "abc004abc004abc004abc004abc004abc004abc0",
      version: 2,
      action: "update",
      message: "fix imports in auth API",
      date: "2026-03-29T14:20:00Z",
      stack: "D1v2,D2v1,D3v1",
    },
  ],
  "user-authentication/2": [
    {
      snapshotId: "S2",
      snapshotSha: "abc002abc002abc002abc002abc002abc002abc0",
      version: 1,
      action: "create",
      message: "add login form",
      date: "2026-03-29T09:00:00Z",
      stack: "D1v1,D2v1",
    },
  ],
  "user-authentication/3": [
    {
      snapshotId: "S3",
      snapshotSha: "abc003abc003abc003abc003abc003abc003abc0",
      version: 1,
      action: "create",
      message: "add E2E tests",
      date: "2026-03-30T14:00:00Z",
      stack: "D1v1,D2v1,D3v1",
    },
  ],
  "fix-token-refresh/1": [
    {
      snapshotId: "S1",
      snapshotSha: "def001def001def001def001def001def001def0",
      version: 1,
      action: "create",
      message: "handle expired refresh tokens",
      date: "2026-03-27T16:15:00Z",
      stack: "D1v1",
    },
    {
      snapshotId: "S3",
      snapshotSha: "def003def003def003def003def003def003def0",
      version: 2,
      action: "update",
      message: "clear stale tokens on expiry",
      date: "2026-03-28T11:00:00Z",
      stack: "D1v2,D2v1",
    },
    {
      snapshotId: "S5",
      snapshotSha: "def005def005def005def005def005def005def0",
      version: 3,
      action: "update",
      message: "add retry with backoff",
      date: "2026-03-29T10:00:00Z",
      stack: "D1v3,D2v1",
    },
  ],
  "fix-token-refresh/2": [
    {
      snapshotId: "S2",
      snapshotSha: "def002def002def002def002def002def002def0",
      version: 1,
      action: "create",
      message: "add refresh token rotation",
      date: "2026-03-28T09:00:00Z",
      stack: "D1v1,D2v1",
    },
  ],
  "update-api-docs/1": [
    {
      snapshotId: "S1",
      snapshotSha: "eee001eee001eee001eee001eee001eee001eee0",
      version: 1,
      action: "create",
      message: "initial API docs update",
      date: "2026-03-25T10:30:00Z",
      stack: "D1v1",
    },
    {
      snapshotId: "S2",
      snapshotSha: "eee002eee002eee002eee002eee002eee002eee0",
      version: 2,
      action: "update",
      message: "add request/response examples",
      date: "2026-03-26T09:00:00Z",
      stack: "D1v2",
    },
  ],
  "search-redesign/1": [
    {
      snapshotId: "S1",
      snapshotSha: "fff001fff001fff001fff001fff001fff001fff0",
      version: 1,
      action: "create",
      message: "add fuzzy matching",
      date: "2026-03-30T08:15:00Z",
      stack: "D1v1",
    },
  ],
};

// Flat list of all snapshots across all features (for timeline view)
export const mockSnapshotTimeline: Record<string, DiffVersionInfo[]> = {
  "user-authentication": [
    { snapshotId: "S1", snapshotSha: "abc001abc001abc001abc001abc001abc001abc0", version: 1, action: "create", message: "D1: add auth API endpoints", date: "2026-03-28T10:45:00Z", stack: "D1v1" },
    { snapshotId: "S2", snapshotSha: "abc002abc002abc002abc002abc002abc002abc0", version: 1, action: "create", message: "D2: add login form", date: "2026-03-29T09:00:00Z", stack: "D1v1,D2v1" },
    { snapshotId: "S3", snapshotSha: "abc003abc003abc003abc003abc003abc003abc0", version: 1, action: "create", message: "D3: add E2E tests", date: "2026-03-30T14:00:00Z", stack: "D1v1,D2v1,D3v1" },
    { snapshotId: "S4", snapshotSha: "abc004abc004abc004abc004abc004abc004abc0", version: 2, action: "update", message: "D1: fix imports in auth API", date: "2026-03-29T14:20:00Z", stack: "D1v2,D2v1,D3v1" },
  ],
  "fix-token-refresh": [
    { snapshotId: "S1", snapshotSha: "def001def001def001def001def001def001def0", version: 1, action: "create", message: "D1: handle expired refresh tokens", date: "2026-03-27T16:15:00Z", stack: "D1v1" },
    { snapshotId: "S2", snapshotSha: "def002def002def002def002def002def002def0", version: 1, action: "create", message: "D2: add refresh token rotation", date: "2026-03-28T09:00:00Z", stack: "D1v1,D2v1" },
    { snapshotId: "S3", snapshotSha: "def003def003def003def003def003def003def0", version: 2, action: "update", message: "D1: clear stale tokens on expiry", date: "2026-03-28T11:00:00Z", stack: "D1v2,D2v1" },
    { snapshotId: "S5", snapshotSha: "def005def005def005def005def005def005def0", version: 3, action: "update", message: "D1: add retry with backoff", date: "2026-03-29T10:00:00Z", stack: "D1v3,D2v1" },
  ],
};
